%Script to compare between curve of sine and cosine 
% that generated by the CORDIC Algorithm and the expected one 
integer_part = 5 ;
fraction_part = 11 ;


angles = zeros(1081,1);

for i = -360:1:720
    angles(i+361) = i *(pi/180);
end

expected_sine = sin(angles);
expected_cosine = cos(angles);

fileID_sine = fopen('..\RTL\sines_out.txt','r');
fileID_cosine = fopen('..\RTL\cosines_out.txt','r');

sines = zeros(1081,1);
cosines = zeros(1081,1);

sines = fscanf(fileID_sine,"%d");
cosines = fscanf(fileID_cosine,"%d");

sines = (2^-fraction_part).*sines ;
cosines = (2^-fraction_part).*cosines ;

fclose(fileID_sine);
fclose(fileID_cosine);
subplot(1,2,1);
plot(angles,expected_cosine,'b', angles , cosines , 'r' );
subplot(1,2,2);
plot(angles,expected_sine,'b',angles , sines , 'r' );
